Question 1

Write a program that will find all numbers which are divisible by 7 but are not a multiple of 5, between 2000 and 3200 (both included). The numbers obtained should be printed in a list.

Hint: Consider using the range(#begin, #end) method.

In [ ]:
#Q1 List
mylist=[]
for i in range(2000,3201):
  if i%7==0 and i%5!=0:
     mylist.append(i)
mylist


Question 2 

 Write a program that can compute the factorial of a given number. (The factorial of n is the product of all positive integers less than or equal to n.) For example: For factorial(5)= 5 x 4 x 3 x 2 x 1 the result is 120 (i.e. factorial (0)=1).

In [ ]:
#Q2 Factorial
f=1
n=input("Enter a number: ")
for i in range(f,int(n)+1):
  f=f*i
print(f)

Question 3 

With a given integer number n, write a program to generate a dictionary that contains (i, i*i) such that is an integral number between 1 and n (both included). Then, the program should print the dictionary. Suppose the following input is supplied to the program: 8 Then, the output should be: {1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}  

In [ ]:
#Q3 Dictionary
dict={}
n=input("Enter a number: ")
for i in range(1,int(n)+1):
  dict[i]=i*i
dict

Question 4 

Given a non-empty string and an integral n, return a new string where the char at index n has been removed. The value of n will be a valid index of a char in the original string (i.e. n will be in the range 0..len(str)-1 inclusive). 

missing_char('kitten', 1) → 'ktten'    for example here we remove "i" which is located in the index 1

missing_char('kitten', 0) → 'itten'   here we remove "k" which is in the index 0

missing_char('kitten', 4) → 'kittn'   here we remove "e" which is in the index 4

In [ ]:

#Q4 Removing a character


leng=0
while leng==0:
  st=input("Enter a non empty string: ")
  leng=len(st)
print("length of string=",leng)
n=-1
while n<0 or n>=leng:
   n=int(input("Enter an integral (from 0 to length of the string-1): "))

mylist=[]
for i in st:
   mylist.append(i)

for x in range((leng-1)):
  if x>=n:
    if x==leng-1:
      mylist.append("")
    mylist[x]=mylist[(x+1)]
del mylist[(leng-1)]
newst="".join(mylist)
print(newst)




 


Enter a non empty string: congrats
length of string= 8
Enter an integral (from 0 to length of the string-1): 3
conrats


Question 5 

Write a NumPy program to convert a NumPy array into a Python list structure.

Expected output: 

Original array elements: [[0 1] [2 3] [4 5]] 

Array to list: [[0, 1], [2, 3], [4, 5]] 
 

Hint: We can use the to_list() function to ensure the conversion.

In [ ]:
#Q5 Array to list
import numpy as np
r=int(input("Input number of rows: "))
c=int(input("Input number of columns: "))
a=np.random.random((r,c))
print("Array\n",a)
ml=a.tolist()
print("List\n",ml)

Input number of rows: 5
Input number of columns: 6
Array
 [[0.9284724  0.52490171 0.36923534 0.6860444  0.22515402 0.87252922]
 [0.71362949 0.2546018  0.34912115 0.78592556 0.22217301 0.00803968]
 [0.35154571 0.23575779 0.34047432 0.87111578 0.30013383 0.56235804]
 [0.13176676 0.87705107 0.30643231 0.71848348 0.19735603 0.94311011]
 [0.61119126 0.02704087 0.1682454  0.64357657 0.41746396 0.45360425]]
List
 [[0.928472395284963, 0.5249017127867193, 0.36923534262722, 0.6860443953851109, 0.2251540220080328, 0.872529220542676], [0.7136294881631465, 0.25460179599889776, 0.34912114835355423, 0.7859255614551754, 0.2221730138759328, 0.00803968451284609], [0.35154571121865896, 0.23575779088603988, 0.3404743182776674, 0.871115775979509, 0.30013383210679423, 0.5623580445927862], [0.13176675854700282, 0.8770510662097791, 0.3064323091218102, 0.718483477265138, 0.19735602720339274, 0.9431101064569396], [0.6111912595843683, 0.027040873010382827, 0.16824539731738997, 0.6435765699997615, 0.4174639559078

Question 6

Write a NumPy program to compute the covariance matrix of two given arrays. 

Original array1: [0 1 2] 

Original array2: [2 1 0] 

Covariance matrix of the said arrays: [[ 1. -1.] [-1. 1.]]
 

Hint: We can use the np.cov() function to calculate the covariance between these two arrays

In [ ]:
#Q6 covariance matrix
n=int(input("choose an integral number: "))

a1=np.random.random((1,n))
a2=np.random.random((1,n))
cm=np.cov(a1,a2)
print("Array 1: \n",a1)
print("Array 2: \n",a2)
print("Covariance matrix: \n",cm)

Question 7

Question: Write a program that calculates and prints the value according to the given formula: Q= Square root of [(2 * C * D)/H] 

The following are the fixed values of C and H: C is 50. H is 30. 

D is the variable whose values should be input into your program in a comma-separated sequence. (That means D contains more than value)

Example: Let's assume the following comma-separated input sequence is given to the program: 100,150,180 The output of the program should be 18,22,24 

To further explain this, we will obtain a result for each value of D:  Q1= Square root of [(2 * C * 100)/H] =18, Q2= Square root of [(2 * C * 150)/H] = 22 and Q3 = Square root of [(2 * C * 180)/H]  = 24

Hint: If the output received is in decimal form, it should be rounded off to its nearest value. For example, if the output received is 26.0, it should be printed as 26. In case of input data being supplied to the question, it should be assumed to be a console input. 

In [ ]:
#Q7 Pandas Series
from numpy.lib import index_tricks
import pandas as pd
import math
c=50
h=30
n=int(input("choose the number of values to enter: "))

l=[]
for i in range(1,(n+1)):
  print("Value",i)
  x=input()
  l.append(float(x))

d=pd.Series(l)
l2=[]
for j in d:
  v=round(math.sqrt(((2*c*j)/h)))
  l2.append(v)
ind2=[]
for i in range(1,(n+1)):
  y="Q"+str(i)
  ind2.append(y)
result=pd.Series(l2,ind2)
print("\nResult:\n",result)


choose the number of values to enter: 5
Value 1
8
Value 2
9
Value 3
10
Value 4
11
Value 5
12

Result:
 Q1    5
Q2    5
Q3    6
Q4    6
Q5    6
dtype: int64
